### ISSUE TITLE
mapping types will be removed

### ISSUE THREAD

**Issue by stevemao** [AntonBazhal/dynamo2es-lambda#41]
So we should not validate this field

https://www.elastic.co/guide/en/elasticsearch/reference/6.0/removal-of-types.html

**Comment by AntonBazhal** [comment]
Type field is mandatory in ES <6.0, so I'm not a fan of just removing its validation.

**Comment by stevemao** [comment]
Once a major version is bumped we can then only support ES >=6.0

**Comment by AntonBazhal** [comment]
Ehh... No. It does not match our use case.

**Comment by dougmoscrop** [comment]
Seems like it can be some kind of constructor argument or whatever. Specify the ES version. 5 or 6. Default to 5. Some time in the future, the default can change to 6, coinciding with a major version change, but it doesn't have to happen on the next one.
