### ISSUE TITLE
parsedRecord.Keys should not be analysed. They should be as is.

### ISSUE THREAD

**Issue by stevemao** [AntonBazhal/dynamo2es-lambda#43]
If a field of a record is a key, it should not be analysed. So that we can use the `term` query.

https://www.elastic.co/guide/en/elasticsearch/guide/current/_finding_exact_values.html

**Comment by AntonBazhal** [comment]
Whether a field is analyzed or not is defined through mapping. What does it have to do with this library?

**Comment by stevemao** [comment]
Sorry, it is not relevant.
