### ISSUE TITLE
lambda-handler-as-promised depreciation

### ISSUE THREAD

**Issue by anchnk** [AntonBazhal/dynamo2es-lambda#45]
Hi, 

Thank you for the great work there.
I've installed the module to give it a try and I do have two depreciation warnings:

1. `lambda-handler-as-promised` which is now `alpha-lambda`
2. The use of the `DocumentClient` object from the AWS SDK (this one is from the dynamodb-marshaler module so I might create another issue).

As you are contributing to both projects, are you waiting for some changes before upgrading `dynamo2es-lambda` dependencies ? Are there some breaking changes or things that should be considered (sorry for the out of context questions). 

I am willing to bump the dependencies if that's something you didn't have time to do as I plan to try your module for a project.

**Comment by AntonBazhal** [comment]
Hey,

I will try to find time to update both this week, but the external contract is not gonna change, so it is safe to try/use `dynamo2es-lambda` with those two deprecated dependencies.

Cheers

**Comment by anchnk** [comment]
Thank you for quick answer :)

I will leave this issue open until you have time to do so as a reminder if you don't mind.
Also if you don't have time, I can find some time to work on this as well.
As you please !

**Comment by AntonBazhal** [comment]
@anchnk Took more time to get my hands on this than I expected
