### ISSUE TITLE
Use host not hosts in README

### ISSUE THREAD

**Issue by dereklieu** [AntonBazhal/dynamo2es-lambda#5]
Under the example configuration in README.md, the `host` property is listed as `hosts`. 

```hosts: 'your-aws-es-host.amazonaws.com'```

This should just be a singular `host` - see [elasticsearch github page example](https://github.com/elastic/elasticsearch-js#examples).

Thanks!

**Comment by dereklieu** [comment]
Ah it turns out it can be either `host` or `hosts`. [elasticsearch config](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/configuration.html#config-options). So feel free to close this without further action.

**Comment by AntonBazhal** [comment]
Cool. Btw, I'm going to publish new version today with `versionField` support (in PR now), if you are interested.
