### ISSUE TITLE
Bring-your-own client libraries

### ISSUE THREAD

**Issue by compwright** [AntonBazhal/dynamo2es-lambda#55]
Seems like it would be a good idea to put `aws-sdk` and `elasticsearch` in `peerDependencies`, and to make `aws-elasticsearch-client` an optional dependency. This would allow uniformity of the library version used, and allow this library to work with non-AWS ElasticSearch clusters.

We would need to have an option to pass in the `elasticsearch` client instance rather than instantiating one in this library. I'm happy to submit a PR if you're good with this idea.

**Comment by AntonBazhal** [comment]
Sounds good to me. If you can make it happen soon, I'll wait for these changes before the major version bump.

**Comment by compwright** [comment]
Since you're only using the bulk API, I'm thinking this should support the new @elastic/elasticsearch client via https://github.com/compwright/aws-elasticsearch-connector.
