### ISSUE TITLE
DynamoDB streams now emitting MODIFY+REMOVE+INSERT instead of just MODIFY?

### ISSUE THREAD

**Issue by crccheck** [AntonBazhal/dynamo2es-lambda#61]
I'm not sure where else to post this, but I saw some weird errors in `dynamo2es-lambda` starting around Oct 3, 2019. it looks like when I update a DynamoDB record, instead of just a `MODIFY`, the stream is now emitting a `MODIFY` for the record, then removing it with `REMOVE`, then inserting it back again with `INSERT`.

**Comment by AntonBazhal** [comment]
I have not experienced this issue myself and even if this is the case, it's a problem with DynamoDB Streams, not this library. Feel free to re-open if you can find a consistent way to reproduce the issue.
