### ISSUE TITLE
Custom Mapping if index doesn't exists

### ISSUE THREAD

**Issue by fpronto** [AntonBazhal/dynamo2es-lambda#65]
As the title says.

I tried to do the index creation in beforeHook but because is not async, it doesn't create my custom mapping

there is way to do that inside this package?

**Comment by AntonBazhal** [comment]
Can you elaborate on why you want to create an index manually? ES does this for you and you can define your template so that custom mapping is applied to every new index created.

**Comment by fpronto** [comment]
I want a specific mapping for a specific index

I want to tokenize some fields in one way, others in another, because of the type of search I'm implementing

**Comment by AntonBazhal** [comment]
You can use `index_patterns` in your template to match a specific index only.
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html

**Comment by fpronto** [comment]
thanks for your help, i thought that this could be an option
